skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
task_marketplace = "FM6bo4u3EMLxMM5NRappPN3ftNzKd7DV5A3z6XFsBQ87"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
